version: '3'

services:
  app:
    image: openjdk:17
    container_name: my-app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: java -Duser.timezone=Asia/Shanghai -jar app.jar